### ISSUE TITLE
Prevent running in safari-web-extension windows? 

### ISSUE THREAD

**Issue by TS6ix2GaH3q679h5** [quoid/userscripts#434]
One of my userscripts seems to interfere with a Safari extension. I'd like to `@exclude` it somehow in the userscript's code but can't seem to find the right syntax for making that happen. 

Is this not possible, or (more likely) am I just doing something wrong by using:

`@exclude *safari-web-extension*`

**Comment by quoid** [comment]
> seems to interfere with a Safari extension

In what way? Can you provide a bit more detail on what you are trying to do?

**Comment by TS6ix2GaH3q679h5** [comment]
Sure. Well, you may recall I'm the person who was asking previously about the  `@grant GM.closeTab` issue, which was fixed and my Userscript for closing open tabs when I click on the side of the tab now works great. I've been very pleased with it. It's a simple script. I'll reproduce it here:

> // ==UserScript==
> // @name        Close tab by side click
> // @description Adds red side bar to left side of tabs, closes tab when sidebar is clicked
> // @exclude    https://www.example.com/*
> // @exclude    https://www.example2.com/*
> // @noframes
> // @match       https://*/*
> // @grant       GM.closeTab
> // @grant       GM_addStyle
> // @inject-into content
> // ==/UserScript==
> 
> var style = document.createElement('style');
>   style.innerHTML = `
>   body {
>   border-left: solid 20px darkred !important;
>   }
>   `;
>   document.head.appendChild(style);
> 
> document.addEventListener("click",function (event) { 
>         if(event.pageX < 20 ) {
>         GM.closeTab();
>         }
> });

This has been working fantastic for me, with one problem: 

For some reason, I can't auto-fill with the [Bitwarden password manager Safari extension](https://bitwarden.com/help/install-safari-app-extension/) when this Userscript is active. Attempting to click a password login entry in the Bitwarden pop-up will force close the tab I'm on. Disabling this userscript regains normal functionality. 

So my best theory is that maybe I can somehow add the "page" that the extension is using to the `@exclude` parameter?  If I could somehow add `safari-web-extension://[long identifying number string here]/popup/index.html*` to it, since that is the URL of the extension's popup, maybe it would work? In this case I'm not sure about the syntax for excluding an extension-based "page" or if it's even possible. 

Although, I can't be fully sure this would work, since although clicking to autofill somehow triggers the close-tab behavior (which I presume is coming from my userscript), the red bar the script is meant to add isn't visible in the Extension pop-up. So it might not be fully related to this.

All I know for sure is that when the userscript is enabled, Bitwarden autofill fails and the tab automatically closes. Disable it, and full functionality returns.

I'm sorry to talk too much about this specifically since it feels like this is somehow a userscript code issue and may not be a Userscript (your extension) issue.

**Comment by TS6ix2GaH3q679h5** [comment]
Just to add more detail: the effect happens even when the `@include` is limited to a single domain. Ex: limiting it to just Google pages prevents BitWarden from logging me into Google because tapping the auto-fill entry will suddenly close the current Google tab. So it seems my idea of using `@exclude` wouldn't work here.

Is there perhaps some way, maybe similar to the `@noframes` argument, that I could instruct the Userscript manager to apply my script *only* to the current actual tab, and not BitWarden's pop-up extension? Assuming this is what's going on, of course.

**Comment by quoid** [comment]
@TS6ix2GaH3q679h5 To be clear you are saying that your userscript is being injected into another extensions popup? (I am to make sure I am understanding correctly)

If the above is correct, that is certainly odd. I wouldn't expect that.

As a quick suggestions, could you not just get `window.location.href` and if it starts with `safari` not trigger the close?

```js
document.addEventListener("click", function (event) {
    if (event.pageX < 20 && !window.location.href.includes("safari-web-extension")) {
        GM.closeTab();
    }
});
```

**Comment by TS6ix2GaH3q679h5** [comment]
I tried adjusting the userscript per your code, but I'm still getting the same behavior. I just can't figure out where this is coming from. 

As per your question, no, it's not that clicking the BitWarden extension icon in the Safari toolbar triggers the close. It's that actually clicking the vault entry in the BitWarden pop-up does it. So, normal behavior (and the behavior when I disable my userscript) is that I click the BitWarden icon in Safari toolbar, pop-up appears, I choose the right login entry, click it, and it populates the username/password field in the tab I'm viewing. Normal auto-fill behavior. 

My quirky behavior is that I can open the BitWarden extension just fine, the list of logins appears, and the moment I click the entry to have it auto-filled, the entire tab closes out. Not just the little pop-up, but the entire tab of the page I was viewing.

I can't figure out why my userscript would be causing this. It's clearly the userscript, since disabling it (not disabling the whole Userscripts extension, just this particular userscript) returns to normal. But I can't figure out why! I'm certainly no expert in this though. And it's not just a click within 20px of the `pageX` either as my script is coded to do; anywhere in the auto-fill entry bar! I just don't get it. Also, if no login field is visible on the page, this behavior will not happen. It's only when trying to autofill. I wonder if somehow the attempt at pasting the login credentials is triggering the `GM.closeTab`?

**Comment by quoid** [comment]
@TS6ix2GaH3q679h5 

If you could provide a short video clip of the behavior, it would make what is going on more clear. All Apple devices have a built in way to record the screen. You could use QuickTime on the mac.

I am still not 100% sure what is going on, so I will wait until i see the behavior before recommending anything.

**Comment by TS6ix2GaH3q679h5** [comment]
I might add that adding an `@exclude` for the actual tab I'm viewing (not for the extension, assuming the `safari-web-extension` syntax) obviously prevents my userscript from running and thus prevents the behavior I'm talking about. So I can deduce that I was wrong that trying to exclude the extension would do anything. It must not be related to the BitWarden extension pop-up itself; must be something in the page.

**Comment by TS6ix2GaH3q679h5** [comment]
It's ok, I appreciate your help. I can't seem to screen record without my credit card entries showing up in the password manager! I will keep playing around and see if I can identify the source of this and post any updates. Sorry to bother about this. Must be just something with my code rather than the extension itself so not your area anyway! Thanks again.

**Comment by TS6ix2GaH3q679h5** [comment]
You know I probably should have mentioned this, but the same behavior happens here on GitHub too. Any time I hit the "Comment" button when I send replies here, the whole tab shuts out. I have to do a quick Command-Shift-T to get back to it. Same thing: disable my userscript, problem goes away. Weird. Anything else, I'll post an update. Thanks again.

**Comment by quoid** [comment]
Test

**Comment by quoid** [comment]
> Any time I hit the "Comment" button

Yeah, there's certainly a problem with the code, just tested it with the comment button. I'd revise the approach you are using.

**Comment by TS6ix2GaH3q679h5** [comment]
I'll give it a try. Thank you very much. I have much to learn.
